import type { Metadata } from "next";
import "./globals.css";
import AOSInitializer from "@/components/AOSInitializer";

export const metadata: Metadata = {
  title: "Abhay-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AOSInitializer /> {/* 👈 Mounts AOS globally */}
        {children}
      </body>
    </html>
  );
}
